package gt.gob.mineco.bancosrgm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2023-11-05T12:59:15.622-06:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos", name = "PagoServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagoServicePortType {

    @WebMethod(action = "getUsuarioRGM")
    @WebResult(name = "revertBoletaRGMResponse", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos", partName = "revertBoletaRGMResponse")
    public RevertBoletaRGMResponse revertBoletaRGM(

        @WebParam(partName = "revertBoletaRGMRequest", name = "revertBoletaRGMRequest", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos")
        RevertBoletaRGMRequest revertBoletaRGMRequest
    );

    @WebMethod(action = "getUsuarioRGM")
    @WebResult(name = "getUsuarioRGMResponse", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos", partName = "getUsuarioRGMResponse")
    public GetUsuarioRGMResponse getUsuarioRGM(

        @WebParam(partName = "getUsuarioRGMRequest", name = "getUsuarioRGMRequest", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos")
        GetUsuarioRGMRequest getUsuarioRGMRequest
    );

    @WebMethod(action = "getUsuarioRGM")
    @WebResult(name = "setBoletaRGMResponse", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos", partName = "setBoletaRGMResponse")
    public SetBoletaRGMResponse setBoletaRGM(

        @WebParam(partName = "setBoletaRGMRequest", name = "setBoletaRGMRequest", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos")
        SetBoletaRGMRequest setBoletaRGMRequest
    );

    @WebMethod(action = "getUsuarioRGM")
    @WebResult(name = "confirmBoletaRGMResponse", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos", partName = "confirmBoletaRGMResponse")
    public ConfirmBoletaRGMResponse confirmBoletaRGM(

        @WebParam(partName = "confirmBoletaRGMRequest", name = "confirmBoletaRGMRequest", targetNamespace = "https://operaciones.rgm.gob.gt/rug-rgm-ws/Pagos")
        ConfirmBoletaRGMRequest confirmBoletaRGMRequest
    );
}
